/* eslint-disable no-secrets/no-secrets */
import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateTaskTable1633572182798 implements MigrationInterface {
  name = 'CreateTaskTable1633572182798';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE "task" (
          "id" number GENERATED BY DEFAULT AS IDENTITY,
          "text" varchar2(255) NOT NULL,
          "done" number DEFAULT 0 NOT NULL,
          "createdAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
          "updatedAt" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
          CONSTRAINT "PK_fb213f79ee45060ba925ecd576e" PRIMARY KEY ("id")
        )`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "task"`);
  }
}
/* eslint-enable */
